#????

spring.application.name=Personal Productivity Agent

# ????????????? --spring.profiles.active=prod ??
spring.profiles.active=dev

# ?? OSIV????????????????
spring.jpa.open-in-view=false

# ===== DeepSeek ?? =====
spring.ai.deepseek.api-key=${DEEPSEEK_API_KEY}
spring.ai.deepseek.chat.model=deepseek-chat
